name: irondash_plus_message_channel
description: Dart interface to irondash_plus MessageChannel.
version: 0.7.0
homepage: https://github.com/SIDL-C0R0RATI0N/irondash_plus

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
